const CATEGORIES = [
  {
    id: "main",
    nameRO: "Fel Principal",
    nameEN: "Mains",
    img: "assets/photos/FelPrincipal.jpg",
    descRO: "Preparate sățioase, cu mai puține calorii.",
    descEN: "Hearty mains with fewer calories.",
  },
  {
    id: "dessert",
    nameRO: "Desert",
    nameEN: "Dessert",
    img: "assets/photos/AlbaCaZapada.png",
    descRO: "Dulce fără vină.",
    descEN: "Sweet without the guilt.",
  },
  {
    id: "soup",
    nameRO: "Ciorbă",
    nameEN: "Soup",
    img: "assets/photos/Ciorba.jpg",
    descRO: "Confort în bol.",
    descEN: "Comfort in a bowl.",
  },
  {
    id: "special",
    nameRO: "Rețete speciale",
    nameEN: "Special Recipes",
    img: "assets/photos/ReteteSpeciale.jpg",
    descRO: "Colecții tematice și exclusivități.",
    descEN: "Thematic collections & exclusives.",
  },
];

// Minimal recipe records
const RECIPES = [
  {
    id: "r1",
    title: "Turbo Veggie Soup",
    lang: { ro: "Supă Turbo de Legume", en: "Turbo Veggie Soup" },
    teaser: "Ușoară și plină de nutrienți.",
    img: "assets/photos/FelPrincipal.jpg",
    free: true,
    category: "soup",
    vegan: true,
    author: "FoodieR",
    price: 15,
    oldPrice: 29,
    kcal: 160,
    carbs: 22,
    protein: 6,
    fat: 3,
    ingredients: ["1 ceapă", "2 morcovi", "1 dovlecel", "apă, sare, piper"],
    steps: ["Călește ceapa", "Adaugă legumele", "Fierbe 20 min", "Blendează."],
  },

  {
    id: "r2",
    title: "Ciorbă de legume turbo",
    lang: { ro: "Ciorbă de legume turbo", en: "Turbo Veggie Soup" },
    teaser: "Ușoară și plină de nutrienți.",
    img: "assets/photos/AlbaCaZapada.png",
    free: true,
    category: "soup",
    vegan: true,
    kcal: 120,
    carbs: 18,
    protein: 4,
    fat: 3,
    ingredients: ["morcov", "țelină", "ardei", "dovlecel", "roșii"],
    steps: ["Taie legumele", "Fierbe 20 min", "Potrivește de sare"],
  },

  {
    id: "r3",
    title: "Lemon Cheesecake Light",
    lang: { ro: "Cheesecake cu lămâie", en: "Lemon Cheesecake" },
    teaser: "Desert fresh, cu mai puțin zahăr.",
    img: "assets/photos/Colaboration.png",
    free: true,
    category: "dessert",
    vegan: false,
    kcal: 210,
    carbs: 24,
    protein: 10,
    fat: 8,
    ingredients: [
      "250 g brânză slabă",
      "iaurt grecesc light",
      "gelatină",
      "lămâie",
    ],
    steps: ["Amestecă baza", "Încorporează gelatina", "Toarnă și răcește 3h"],
  },

  {
    id: "r4",
    title: "Veggie Wrap Rapid",
    lang: { ro: "Wrap de legume rapid", en: "Quick Veggie Wrap" },
    teaser: "Prânz la pachet în 10 minute.",
    img: "assets/photos/FelPrincipal.jpg",
    free: true,
    category: "main",
    vegan: true,
    kcal: 320,
    carbs: 44,
    protein: 11,
    fat: 10,
    ingredients: ["lipie integrală", "hummus", "salată", "ardei", "roșii"],
    steps: ["Unge lipia cu hummus", "Adaugă legumele", "Rulează și servește"],
  },

  {
    id: "r5",
    title: "Salată de quinoa",
    lang: { ro: "Salată de quinoa", en: "Quinoa Salad" },
    teaser: "O salată ușoară și plină de nutrienți.",
    img: "assets/photos/ReteteSpeciale.jpg",
    free: true,
    category: "salad",
    vegan: true,
    kcal: 250,
    carbs: 30,
    protein: 8,
    fat: 5,
    ingredients: ["quinoa", "roșii", "castraveți", "ulei de măsline"],
    steps: ["Fierbe quinoa", "Taie legumele", "Amestecă totul"],
  },

  {
    id: "r6",
    title: "Raluca gătește low carb, low fat, high protein",
    lang: {
      ro: "Raluca gătește low carb, low fat, high protein",
      en: "Raluca cooks low carb, low fat, high protein",
    },
    teaser: "O rețetă sănătoasă și gustoasă.",
    img: "assets/photos/ReteteSpeciale.jpg",
    free: true,
    category: "main",
    vegan: false,
    kcal: 250,
    carbs: 20,
    protein: 25,
    fat: 7,
    ingredients: ["piept de pui", "legume", "condimente", "ulei de măsline"],
    steps: ["Gătește puiul", "Pregătește legumele", "Amestecă și servește"],
  },

  {
    id: "r7",
    title: "Brownie de fasole neagră",
    lang: { ro: "Brownie de fasole neagră", en: "Black Bean Brownie" },
    teaser: "Ciocolatos și surprinzător de lejer.",
    img: "assets/photos/Colaboration.png",
    free: false,
    category: "dessert",
    vegan: true,
    kcal: 210,
    carbs: 25,
    protein: 8,
    fat: 7,
    ingredients: ["fasole neagră fiartă", "cacao", "ovăz", "banană"],
    steps: ["Blenduiește", "Toarnă în tavă", "Coace 18 min"],
  },

  {
    id: "r8",
    title: "Pizza proteinată la tigaie",
    lang: { ro: "Pizza proteinată la tigaie", en: "Skillet Protein Pizza" },
    teaser: "Blat rapid din iaurt și făină integrală.",
    img: "assets/photos/ReteteSpeciale.jpg",
    free: true,
    category: "main",
    vegan: false,
    kcal: 330,
    carbs: 30,
    protein: 30,
    fat: 10,
    ingredients: [
      "iaurt",
      "făină integrală",
      "sos roșii",
      "șuncă de curcan",
      "mozzarella light",
    ],
    steps: [
      "Frământă blatul",
      "Prăjește ușor",
      "Adaugă topping și acoperă 5 min",
    ],
  },

  {
    id: "r9",
    title: "No-bake Cheesecake",
    lang: { ro: "Cheesecake fără coacere", en: "No-bake Cheesecake" },
    teaser: "Cremă catifelată, îndulcită responsabil.",
    img: "assets/photos/ReteteSpeciale.jpg",
    free: true,
    sale: true,
    category: "dessert",
    vegan: false,
    price: 15,
    oldPrice: 29,
    kcal: 260,
    carbs: 21,
    protein: 12,
    fat: 9,
    ingredients: [
      "cremă de brânză",
      "smântână",
      "îndulcitor",
      "biscuiți integrali",
    ],
    steps: ["Pregătește baza", "Amestecă crema", "Lasă la rece 4h"],
  },

  {
    id: "r10",
    title: "Green Pasta",
    lang: { ro: "Paste verzi", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/FelPrincipal.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: true,
    price: 12,
    oldPrice: 24,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
  {
    id: "r10",
    title: "Green Pasta",
    lang: { ro: "Paste verzi", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/FelPrincipal.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: true,
    price: 12,
    oldPrice: 24,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
  {
    id: "r10",
    title: "Green Pasta",
    lang: { ro: "Paste verzi", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/FelPrincipal.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: true,
    price: 12,
    oldPrice: 24,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
];

// Blog posts
const BLOG = [
  {
    id: "b1",
    title: "Mindful eating în 5 pași",
    excerpt: "Mic ghid pentru a mânca prezent.",
    img: "assets/hero-main.jpg",
  },
  {
    id: "b2",
    title: "Cum reduc sarea fără să pierd gustul",
    excerpt: "Trucuri pentru a condimenta deștept.",
    img: "assets/hero-soup.jpg",
  },
];

// Example menus
const MENUS = [
  {
    id: "m1",
    title: "Meniu 1600 kcal",
    items: [
      "Mic dejun: bowl proteic",
      "Prânz: Lasagna ușoară",
      "Cină: Ciorbă de legume",
    ],
  },
  {
    id: "m2",
    title: "Meniu vegan 1800 kcal",
    items: [
      "Mic dejun: Overnight oats",
      "Prânz: Brownie? De ce nu!",
      "Cină: Supă densă de legume",
    ],
  },
];
