const CATEGORIES = [
  {
    id: "main",
    nameRO: "Fel Principal",
    nameEN: "Mains",
    img: "assets/photos/FelPrincipal.jpg",
    descRO: "Preparate sățioase, cu mai puține calorii.",
    descEN: "Hearty mains with fewer calories.",
  },
  {
    id: "dessert",
    nameRO: "Desert",
    nameEN: "Dessert",
    img: "assets/photos/AlbaCaZapada.png",
    descRO: "Dulce fără vină.",
    descEN: "Sweet without the guilt.",
  },
  {
    id: "soup",
    nameRO: "Ciorbă",
    nameEN: "Soup",
    img: "assets/photos/Ciorba.jpg",
    descRO: "Confort în bol.",
    descEN: "Comfort in a bowl.",
  },
  {
    id: "special",
    nameRO: "Rețete speciale",
    nameEN: "Special Recipes",
    img: "assets/photos/ReteteSpeciale.jpg",
    descRO: "Colecții tematice și exclusivități.",
    descEN: "Thematic collections & exclusives.",
  },
];

// Minimal recipe records
const RECIPES = [
  {
    id: "r1",
    title: "Lasagna ușoară cu dovlecel",
    lang: { ro: "Lasagna ușoară cu dovlecel", en: "Light Zucchini Lasagna" },
    category: "main",
    price: 19,
    sale: true,
    free: false,
    vegan: false,
    kcal: 380,
    carbs: 32,
    protein: 28,
    fat: 12,
    img: "assets/placeholders/recipe-1.jpg",
    teaser: "Toată savoarea, cu mai puține foi și brânză light.",
    ingredients: [
      "200g dovlecel feliat",
      "200g carne curcan",
      "100g brânză light",
      "sos roșii",
    ],
    steps: [
      "Sotează carnea cu condimente.",
      "Așază straturi alternative cu dovlecel și sos.",
      "Coace 25 min la 190°C.",
    ],
  },
  {
    id: "r2",
    title: "Cheesecake fără coacere",
    lang: { ro: "Cheesecake fără coacere", en: "No‑bake Cheesecake" },
    category: "dessert",
    price: 15,
    sale: true,
    free: false,
    vegan: false,
    kcal: 240,
    carbs: 28,
    protein: 12,
    fat: 8,
    img: "assets/placeholders/recipe-2.jpg",
    teaser: "Cremă catifelată, îndulcită responsabil.",
    ingredients: [
      "200g iaurt grecesc 2%",
      "200g brânză light",
      "îndulcitor",
      "fulgi de ovăz",
    ],
    steps: ["Amestecă baza.", "Întinde crema.", "Răcește 2 ore."],
  },
  {
    id: "r3",
    title: "Ciorbă de legume turbo",
    lang: { ro: "Ciorbă de legume turbo", en: "Turbo Veggie Soup" },
    category: "soup",
    price: 0,
    sale: false,
    free: true,
    vegan: true,
    kcal: 120,
    carbs: 18,
    protein: 4,
    fat: 3,
    img: "assets/placeholders/recipe-3.jpg",
    teaser: "Ușoară și plină de nutrienți.",
    ingredients: ["morcov", "țelină", "ardei", "dovlecel", "roșii"],
    steps: ["Taie legumele.", "Fierbe 20 min.", "Potrivește de sare."],
  },
  {
    id: "r4",
    title: "Brownie de fasole neagră",
    lang: { ro: "Brownie de fasole neagră", en: "Black Bean Brownie" },
    category: "dessert",
    price: 12,
    sale: false,
    free: false,
    vegan: true,
    kcal: 210,
    carbs: 25,
    protein: 8,
    fat: 7,
    img: "assets/placeholders/recipe-4.jpg",
    teaser: "Ciocolatos și surprinzător de lejer.",
    ingredients: ["fasole neagră fiartă", "cacao", "ovăz", "banană"],
    steps: ["Blenduiește.", "Toarnă în tavă.", "Coace 18 min."],
  },
  {
    id: "r5",
    title: "Pizza proteinată la tigaie",
    lang: { ro: "Pizza proteinată la tigaie", en: "Skillet Protein Pizza" },
    category: "main",
    price: 14,
    sale: false,
    free: false,
    vegan: false,
    kcal: 330,
    carbs: 30,
    protein: 30,
    fat: 10,
    img: "assets/placeholders/recipe-5.jpg",
    teaser: "Blat rapid din iaurt și făină integrală.",
    ingredients: [
      "iaurt",
      "făină integrală",
      "sos roșii",
      "șuncă de curcan",
      "mozzarella light",
    ],
    steps: [
      "Frământă blatul.",
      "Prăjește ușor.",
      "Adaugă topping și acoperă 5 min.",
    ],
  },
];

// Blog posts
const BLOG = [
  {
    id: "b1",
    title: "Mindful eating în 5 pași",
    excerpt: "Mic ghid pentru a mânca prezent.",
    img: "assets/hero-main.jpg",
  },
  {
    id: "b2",
    title: "Cum reduc sarea fără să pierd gustul",
    excerpt: "Trucuri pentru a condimenta deștept.",
    img: "assets/hero-soup.jpg",
  },
];

// Example menus
const MENUS = [
  {
    id: "m1",
    title: "Meniu 1600 kcal",
    items: [
      "Mic dejun: bowl proteic",
      "Prânz: Lasagna ușoară",
      "Cină: Ciorbă de legume",
    ],
  },
  {
    id: "m2",
    title: "Meniu vegan 1800 kcal",
    items: [
      "Mic dejun: Overnight oats",
      "Prânz: Brownie? De ce nu!",
      "Cină: Supă densă de legume",
    ],
  },
];
