const CATEGORIES = [
  {
    id: "main",
    nameRO: "Fel Principal",
    nameEN: "Mains",
    img: "assets/photos/FelPrincipal.jpg",
    descRO: "Preparate sățioase, cu mai puține calorii.",
    descEN: "Hearty mains with fewer calories.",
  },
  {
    id: "dessert",
    nameRO: "Desert",
    nameEN: "Dessert",
    img: "assets/photos/AlbaCaZapada.png",
    descRO: "Dulce fără vină.",
    descEN: "Sweet without the guilt.",
  },
  {
    id: "soup",
    nameRO: "Ciorbă",
    nameEN: "Soup",
    img: "assets/photos/Ciorba.jpg",
    descRO: "Confort în bol.",
    descEN: "Comfort in a bowl.",
  },
  {
    id: "special",
    nameRO: "Rețete speciale",
    nameEN: "Special Recipes",
    img: "assets/photos/ReteteSpeciale.jpg",
    descRO: "Colecții tematice și exclusivități.",
    descEN: "Thematic collections & exclusives.",
  },
];

// Minimal recipe records
const RECIPES = [
  {
    id: "r1",
    title: "Ciorbă cu perișoare din piept de pui",
    lang: {
      ro: "Ciorbă cu perișoare din piept de pui",
      en: "Turbo Veggie Soup",
    },
    teaser: "Ciorbă gustoasă cu perișoare fragede din carne și legume.",
    img: "assets/photos/CiorbaPerisoare.jpg",
    free: true,
    category: "soup",
    vegan: false,
    author: "FoodieR",
    price: 15,
    oldPrice: 29,
    kcal: 160,
    carbs: 22,
    protein: 6,
    fat: 3,
    ingredients: ["1 ceapă", "2 morcovi", "1 dovlecel", "apă, sare, piper"],
    steps: ["Călește ceapa", "Adaugă legumele", "Fierbe 20 min", "Blendează."],
  },

  {
    id: "r2",
    title: "Boabe de naut *produs vegan",
    lang: { ro: "Boabe de naut *produs vegan", en: "Turbo Veggie Soup" },
    teaser: "O gustare crocantă și sănătoasă, plină de proteine vegetale.",
    img: "assets/photos/BoabeNaut.jpg",
    free: true,
    //category: "soup",
    vegan: true,
    kcal: 120,
    carbs: 18,
    protein: 4,
    fat: 3,
    ingredients: ["morcov", "țelină", "ardei", "dovlecel", "roșii"],
    steps: ["Taie legumele", "Fierbe 20 min", "Potrivește de sare"],
  },

  {
    id: "r3",
    title: "Briose *produs vegan",
    lang: { ro: "Briose *produs vegan", en: "Lemon Cheesecake" },
    teaser:
      "Pufoase și aromate, perfecte pentru o pauză dulce fără produse de origine animală.",
    img: "assets/photos/BrioseVegane.jpg",
    free: true,
    category: "dessert",
    vegan: false,
    kcal: 210,
    carbs: 24,
    protein: 10,
    fat: 8,
    ingredients: [
      "250 g brânză slabă",
      "iaurt grecesc light",
      "gelatină",
      "lămâie",
    ],
    steps: ["Amestecă baza", "Încorporează gelatina", "Toarnă și răcește 3h"],
  },

  {
    id: "r4",
    title: "Burgher *produs vegan",
    lang: { ro: "Burgher *produs vegan", en: "Quick Veggie Wrap" },
    teaser: "Chiflă proaspătă cu legume crocante si nutritive.",
    img: "assets/photos/BurgherVegan.jpg",
    free: true,
    category: "main",
    vegan: true,
    kcal: 320,
    carbs: 44,
    protein: 11,
    fat: 10,
    ingredients: ["lipie integrală", "hummus", "salată", "ardei", "roșii"],
    steps: ["Unge lipia cu hummus", "Adaugă legumele", "Rulează și servește"],
  },

  {
    id: "r5",
    title: "Ciorba rosie",
    lang: { ro: "Ciorba rosie *produs vegan", en: "Quinoa Salad" },
    teaser:
      "O ciorbă acrișoară cu sfeclă și cartofi, plină de vitamine și savoare.",
    img: "assets/photos/CiorbaRosie.jpg",
    free: true,
    category: "salad",
    vegan: true,
    kcal: 250,
    carbs: 30,
    protein: 8,
    fat: 5,
    ingredients: ["quinoa", "roșii", "castraveți", "ulei de măsline"],
    steps: ["Fierbe quinoa", "Taie legumele", "Amestecă totul"],
  },

  {
    id: "r6",
    title: "Papanasi",
    lang: {
      ro: "Papanasi",
      en: "Raluca cooks low carb, low fat, high protein",
    },
    teaser: "Desert cu brânză dulce, servit cu smântână și dulceață.",
    img: "assets/photos/Papanasi.jpg",
    free: true,
    category: "dessert",
    vegan: false,
    kcal: 250,
    carbs: 20,
    protein: 25,
    fat: 7,
    ingredients: ["piept de pui", "legume", "condimente", "ulei de măsline"],
    steps: ["Gătește puiul", "Pregătește legumele", "Amestecă și servește"],
  },

  {
    id: "r7",
    title: "Salata calda *produs vegan",
    lang: { ro: "Brownie de fasole neagră", en: "Black Bean Brownie" },
    teaser: "Legume sotate ușor, păstrându-și prospețimea și aroma naturală.",
    img: "assets/photos/PizzaLow.jpg",
    free: false,
    category: "main",
    vegan: true,
    kcal: 210,
    carbs: 25,
    protein: 8,
    fat: 7,
    ingredients: ["fasole neagră fiartă", "cacao", "ovăz", "banană"],
    steps: ["Blenduiește", "Toarnă în tavă", "Coace 18 min"],
  },

  {
    id: "r8",
    title: "Shaorma",
    lang: { ro: "Shaorma", en: "Skillet Protein Pizza" },
    teaser: "Lipie proaspătă cu carne fragedă, legume crocante și sos aromat.",
    img: "assets/photos/Shaorma2.jpg",
    free: true,
    category: "main",
    vegan: false,
    kcal: 330,
    carbs: 30,
    protein: 30,
    fat: 10,
    ingredients: [
      "iaurt",
      "făină integrală",
      "sos roșii",
      "șuncă de curcan",
      "mozzarella light",
    ],
    steps: [
      "Frământă blatul",
      "Prăjește ușor",
      "Adaugă topping și acoperă 5 min",
    ],
  },

  {
    id: "r9",
    title: "Pizza Low calories",
    lang: { ro: "Pizza Low calories", en: "No-bake Cheesecake" },
    teaser: "Pizza delicioasa cu mai putine calorii",
    img: "assets/photos/PizzaLow.jpg",
    free: true,
    sale: false,
    category: "main",
    vegan: false,
    price: 15,
    oldPrice: 29,
    kcal: 260,
    carbs: 21,
    protein: 12,
    fat: 9,
    ingredients: [
      "cremă de brânză",
      "smântână",
      "îndulcitor",
      "biscuiți integrali",
    ],
    steps: ["Pregătește baza", "Amestecă crema", "Lasă la rece 4h"],
  },

  {
    id: "r10",
    title: "Green Pasta",
    lang: { ro: "Rulada cu conipida", en: "Green Pasta" },
    teaser:
      "Preparat savuros, cu umplutură de carne fragedă și conopidă aromată.",
    img: "assets/photos/RuladaCotlet.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: false,
    price: 22,
    oldPrice: 28,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
  {
    id: "r11",
    title: "Mancare de ceapa",
    lang: { ro: "Mancare de ceapa", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/MancareCeapa.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: false,
    price: 10,
    oldPrice: 14,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
  {
    id: "r11",
    title: "Gofre",
    lang: { ro: "Gofre", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/GofreFrupt.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: false,
    price: 15,
    oldPrice: 19,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
  {
    id: "r12",
    title: "Fursecuri *produs vegan",
    lang: { ro: "Fursecuri *produs vegan", en: "Green Pasta" },
    teaser: "Rapid, fresh, sățios.",
    img: "assets/photos/FursecuriVegane.jpg",
    free: false,
    sale: true,
    category: "main",
    vegan: true,
    price: 20,
    oldPrice: 25,
    kcal: 300,
    carbs: 50,
    protein: 10,
    fat: 6,
    ingredients: ["paste integrale", "spanac", "usturoi", "ulei de măsline"],
    steps: ["Fierbe pastele", "Sotează spanacul", "Amestecă și servește"],
  },
];

// Blog posts
const BLOG = [
  {
    id: "b1",
    title: "Mindful eating în 5 pași",
    excerpt: "Mic ghid pentru a mânca prezent.",
    img: "assets/hero-main.jpg",
  },
  {
    id: "b2",
    title: "Cum reduc sarea fără să pierd gustul",
    excerpt: "Trucuri pentru a condimenta deștept.",
    img: "assets/hero-soup.jpg",
  },
];

// Example menus
const MENUS = [
  {
    id: "m1",
    title: "Meniu 1600 kcal",
    items: [
      "Mic dejun: bowl proteic",
      "Prânz: Lasagna ușoară",
      "Cină: Ciorbă de legume",
    ],
  },
  {
    id: "m2",
    title: "Meniu vegan 1800 kcal",
    items: [
      "Mic dejun: Overnight oats",
      "Prânz: Brownie? De ce nu!",
      "Cină: Supă densă de legume",
    ],
  },
];
